version: '3.2'

services:

  elasticsearch1:
    container_name: elasticsearch1
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    hostname: elasticsearch1
    environment:
      - bootstrap.memory_lock=true
      - node.name=elasticsearch1
      - cluster.name=elasticsearch-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - discovery.seed_hosts=elasticsearch2
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - elastic1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic_net
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
  
  elasticsearch2:
    container_name: elasticsearch2
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    hostname: elasticsearch2
    environment:
      - bootstrap.memory_lock=true
      - node.name=elasticsearch2
      - cluster.name=elasticsearch-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - discovery.seed_hosts=elasticsearch1
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - elastic2:/usr/share/elasticsearch/data
    networks:
      - elastic_net
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.10.2
    depends_on:
      elasticsearch1:
        condition: service_healthy
    environment:
      ELASTICSEARCH_URL: http://elasticsearch1:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch1:9200","http://elasticsearch2:9200"]' 
    ports:
      - 5601:5601
    networks:
      - elastic_net
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

networks:
  elastic_net:
    name: elastic_net
    driver: bridge

volumes:
  elastic1:
    driver: local
  elastic2:
    driver: local